nossas/cms

app/contrib/bonde/backends.py
Corrigindo o erro de acesso não autorizado retornando Status 500
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204959092942506
=> Fix: Auth login

app/admin_styled/admin.py
No campo de seleção do template alterar "----" para "Criar página do zero"
=> Altera label de Adicionar Página de ----- para Nova Página do Zero

app/eleicao/templates/eleicao/candidate_wizard_form.html, app/tailwind/static/tailwind/tailwindcss/eleicao.css
Adiciona estilos ao Steps do Candidate Wizard Form
https://app.asana.com/0/1161468210277385/1205210845711904
=> Adiciona estilos ao Steps do Candidate Wizard Form

app/eleicao/templates/eleicao/candidate_wizard_form.html
Adiciona o atributo `formnovalidate` no button Voltar.
https://app.asana.com/0/1161468210277385/1205210845711903
=> Adiciona "formnovalidate" attr no botão de Voltar

app/eleicao/models.py, app/eleicao/templates/eleicao/candidate_wizard_form.html, app/eleicao/urls.py, app/eleicao/views.py
##
Bug no upload de arquivos
https://app.asana.com/0/1161468210277385/1205210845711905
=> Upload de arquivos 

app/eleicao/csv/states.csv, app/eleicao/forms/create.py, app/eleicao/templates/eleicao/candidate_wizard_form.html
=> Adicionar erros de validação

.github/PULL_REQUEST_TEMPLATE.md
Adiciona template de Pull Request - só porque queria automatizar a escrita desses PRs todos com tudo detalhadinho :sparkles:
=> Chore: Adiciona template de Pull Request

app/admin_styled/admin.py, app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/base.html, app/eleicao/templates/eleicao/eleicao_template.html, app/eleicao/templates/eleicao/plugins/candidate_list.html, app/eleicao/templates/eleicao/plugins/navbar.html, app/eleicao/templates/eleicao/templatetags/menu.html, app/eleicao/templatetags/eleicao_menu_tags.py, app/eleicao/urls.py, app/project/settings/cms.py
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205280553810657
- https://app.asana.com/0/0/1205280553810659
- https://app.asana.com/0/0/1205280553810655
=> Feature: Modelo de página para A Eleição do Ano

app/eleicao/middleware.py, app/project/middleware.py, app/project/settings/base.py
Adicionar redirecionamento de `www` para domínios sem o `www`
Configurar variáveis de ambiente para o domínio **aeleicaodoano.com**
=> Feature: Redirecionamento de domínios e subdomínios

app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/candidate_wizard_form.html, app/eleicao/templates/eleicao/plugins/carousel.html, app/project/settings/cms.py, app/tailwind/static/tailwind/tailwindcss/eleicao.css
Adiciona CarouselPlugin e icons/textos estáticos
https://app.asana.com/0/1161468210277385/1205280553810660
=> Adiciona o Carousel Plugin no CMS

app/admin_styled/templates/admin_styled/widgets/select_layout_option/five_columns.svg, app/contrib/frontend/grid/models.py, app/contrib/frontend/landpage/forms.py, app/contrib/frontend/landpage/layouts.py
Adiciona o grid de 5 colunas no app frontend
https://app.asana.com/0/1161468210277385/1205301247662265
=> feat:add-5-grid

app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/plugins/navbar.html
Adiciona customização de Background Color na EleicaoNavbarPlugin
https://app.asana.com/0/1161468210277385/1205315214941534
=> Feature: Adiciona customização de Background Color na Navbar

app/eleicao/forms/candidate.py, app/eleicao/forms/fields.py, app/eleicao/views.py
Resolver problema com recaptcha no Cadastro de Candidatura
https://github.com/torchbox/django-recaptcha/issues/115
=> fix(eleicao): add snippet to use recaptcha and formtools steps

app/eleicao/templates/eleicao/includes/candidate_social_media.html, app/eleicao/templatetags/eleicao_share_tags.py
URLs de social media não possuem padrão no Perfil da Candidatura
=> fix(eleicao): parse social media urls to render on candidate detail

app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/plugins/candidate_list.html, app/eleicao/templates/eleicao/plugins/card.html
Resolver o dinamismo do layout para o bloco de items da lista e a responsividade dos elementos da página
- https://app.asana.com/0/1161468210277385/1205324039429944/f
=> Fix: Ajustes na Listagem de Candidaturas

app/eleicao/places/views.py
Ordenar seleção de cidades por ordem alfabetica A-Z
=> feat(eleicao): add ordering to cities on search address

app/eleicao/templates/eleicao/includes/candidate_object_detail.html, app/eleicao/templates/eleicao/includes/candidate_social_media.html, app/eleicao/templates/eleicao/templatetags/social_media.html, app/eleicao/templatetags/eleicao_share_tags.py
=> fix(eleicao): use tag to parse and render social medias

app/eleicao/views.py
Adicionando ensagem para compartilhamento por Twitter e Whatsapp pós inscrição candidata:
https://app.asana.com/0/1161468210277385/1205324039429964
=> feat:adicionando mensagem no modal de candidato

app/eleicao/templates/eleicao/candidate_detail.html, app/eleicao/templates/eleicao/plugins/navbar.html, app/tailwind/static/tailwind/tailwindcss/eleicao.css
Refatora Links da Navbar no Mobile
- https://app.asana.com/0/1161468210277385/1205346197709206/f
**Bonus**
=> Fix: Links da Navbar no Mobile

app/eleicao/templates/eleicao/candidate_detail.html, app/eleicao/templates/eleicao/includes/candidate_share.html, app/eleicao/templates/eleicao/plugins/carousel.html, app/tailwind/static/tailwind/tailwindcss/eleicao.css
Adiciona a biblioteca Swiper no CarouselPlugin
- https://app.asana.com/0/1161468210277385/1205367427032529/f
- `swiper` adicionado via CDN
=> Fix: Adiciona a biblioteca Swiper no CarouselPlugin

app/eleicao/templates/eleicao/icons/filter-icon.svg, app/eleicao/templates/eleicao/includes/agree_input.html, app/eleicao/templates/eleicao/includes/card.html, app/tailwind/static/tailwind/tailwindcss/eleicao.css
Adiciona "target="_blank" ao card de Candidate e refatora o css `filter` dos Agree de Termo de Compromisso para garantir compatibilidade com iOS.
=> Fix: Adiciona "target="_blank" ao card de Candidate e refatora "filter" dos Agree de Termo de Compromisso

app/eleicao/templatetags/eleicao_share_tags.py
Muda Regex para aceitar "." e adiciona validação para "@"
=> Fix(eleicao): Muda Regex para aceitar "." e adiciona validação para "@"

app/eleicao/cms_plugins.py
Resolve bug para mostrar as candidaturas do CT que a pessoa eleitora colocar no formulário.
=> Fix: Resolve bug de pesquisa por CT

app/eleicao/templatetags/eleicao_share_tags.py
Quando o candidato preenche o formulário e não seleciona o tipo de rede social Facebook apenas adiciona o link para o seu facebook temos um erro.
=> fix(eleicao): change attr access on render_social_media tag

app/eleicao/cms_plugins.py, app/eleicao/forms/filters.py, app/eleicao/static/js/widgets/cep-fields.js, app/eleicao/templates/eleicao/filters/candidate_list_filter.html, app/eleicao/templates/eleicao/plugins/candidate_list.html
Adiciona filtro de cidade na Lista de Candidaturas
=> Feat: Adiciona filtro de cidade na Lista de Candidaturas

app/eleicao/templates/eleicao/plugins/candidate_list.html
Adiciona filter_city nos parametros da URL dentro da Paginação
=> Fix: Adiciona filter_city nos parametros da URL dentro da Paginação

app/contrib/frontend/grid/cms_plugins.py, app/contrib/frontend/landpage/plugin_base.py, app/project/settings/cms.py
Adiciona MapPlugin dentro de Block e Column plugin
=> Fix: Adiciona MapPlugin dentro de Block e Column plugin 

app/contrib/frontend/maps/static/maps/js/maps.js
Adiciona propriedades no tooltip do Mapa
=> Fix: Adiciona propriedades no tooltip do Mapa

app/contrib/frontend/landpage/templates/frontend/landpage/plugins/navbar.html
=> Fix: Adiciona top na Navbar

app/contrib/campaign/cms_wizards.py, app/contrib/campaign/forms.py, app/contrib/frontend/landpage/forms.py, app/contrib/frontend/landpage/layouts.py
Adiciona no `wizard form` o botão de Criar Campanha de Pressão e Subpágina. Esses botões podem reduzir o fluxo de criação de página em 1 click. 
1:
2:
=> feat(campaign): add wizard to create pressure campaign

app/nossas/plugins/cms_plugins/button.py, app/nossas/plugins/forms/buttonform.py
Muda nome da classe de MyLinkPlugin para LinkButtonPlugin. E adiciona a tradução para o nome do plugin  `Link / Botão`
=> Feature: Muda nome de MyLinkPlugin para LinkButtonPlugin

app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/templates/nossas/footer_menu.html, app/nossas/design/templates/nossas/footer_submenu.html, app/nossas/plugins/templates/nossas/plugins/site_footer.html
O Footer deve renderizar em 2 layouts diferentes para versões Desktop (≥768px) e Mobile (<768px)
**Versão Desktop**
**Versão Mobile**
- Executar migrações
=> Ajustes no Footer do Site NOSSAS

app/nossas/apps/campaigns/templates/plugins/filter_campaign_list_plugin_item.html, app/nossas/apps/campaigns/templates/plugins/navigate_campaigns_plugin.html, app/nossas/design/static/bootstrap/scss/_variables.scss, app/nossas/design/static/design/scss/campaign.scss, app/nossas/design/static/design/scss/navbar.scss, app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/static/design/scss/reset.scss, app/nossas/design/templates/nossas/includes/menu/button.html, app/nossas/design/templates/nossas/mega_menu.html, app/nossas/design/templates/nossas/menu.html, app/nossas/design/templates/nossas/svg/chevron-down.svg, app/nossas/design/templates/nossas/svg/menu.svg, app/nossas/design/templatetags/design_tags.py, app/nossas/plugins/cms_plugins/box.py, app/nossas/plugins/forms/boxform.py, app/nossas/plugins/models/boxmodel.py, app/nossas/plugins/models/navbarmodel.py, app/nossas/plugins/templates/nossas/plugins/box.html, app/nossas/plugins/templates/nossas/plugins/container.html, app/nossas/plugins/templates/nossas/plugins/header.html, app/nossas/plugins/templates/nossas/plugins/navbar.html, app/nossas/plugins/templates/nossas/plugins/site_footer.html, app/nossas/settings.py
Realiza ajustes gerais de tamanho de fontes, formatos e espaçamentos.
=> Tipografia do Site NOSSAS

app/nossas/apps/templates/plugins/team_accordion_plugin.html, app/nossas/apps/templates/team/member_modal.html, app/nossas/design/static/bootstrap/scss/_accordion.scss, app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/templates/nossas/graphics/group_30_90deg.svg, app/nossas/plugins/templates/nossas/plugins/accordion.html
Adiciona novos estilos para o Acordeon e Acordeon de Time. Altera também o corpo do modal de Colaborador (ao clicar em algum item do Acordeon de Time) e espaçamentos do Acordeon.
Obs: Importante utilizar para as/os colaboradores o tamanho de foto 625x625. Essa é uma limitação por conta do formato da máscara que eu e Igor colocamos no CSS para fazer o recorte de acordo com o Figma.
=> Fix: Modal e espaçamentos de Acordeon de Time e Acordeon

.github/PULL_REQUEST_TEMPLATE.md
Adiciona "Como testar" no PR Template
=> Chore: Adiciona "Como testar" no PR Template

app/nossas/apps/cms_plugins/campaigns.py, app/nossas/apps/forms/campaigns.py, app/nossas/apps/templates/plugins/filter_campaign_list_plugin.html, app/nossas/design/static/design/scss/forms.scss, app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/templatetags/design_tags.py, app/nossas/plugins/templates/nossas/plugins/gallery.html
Adicionar filto de Comunidade, Temática e Ano de Lançamento para plugin de Lista de Campanhas
=> Filtro no plugin de Lista de Campanhas

app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/static/design/scss/video.scss, app/nossas/design/templates/djangocms_video/default/video_player.html, app/nossas/settings.py, app/requirements.txt
Habilitar o plugin de video para o site NOSSAS.
Referência de como usar na documentação do plugin https://github.com/django-cms/djangocms-video
=> feat(nossas): enable video player plugin and styled

app/nossas/design/static/design/scss/nossas.scss, app/nossas/design/templates/nossas/footer_menu.html, app/nossas/plugins/templates/nossas/plugins/site_footer.html
Adiciona classes CSS ao Footer.
- Adicione quatro páginas (as três primeiras devem ter subpáginas)
- Teste a funcionalidade
=> Fix: Adiciona classes CSS ao Footer

app/nossas/apps/templates/plugins/timeline_list.html, app/nossas/apps/templates/plugins/timeline_plugin.html, app/nossas/design/static/design/scss/nossas.scss
À partir. Ao estudar um pouco da estrutura de como scrollbar se comporta nos navegadores ([link 1](https://medium.com/@stheodorejohn/scrollbar-styling-in-chrome-firefox-and-safari-customizing-browser-elements-254c303eceea) e [link 2](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)), em navegadores baseados em webkit, o scroll é calculado como parte do elemento HTML. Esse problema gerou inconsistencia no alinhamento das linhas divisórias do plugin Timeline. Esse PR resolve parte do problema gerado, definindo altura e largura ao scroll de navegadores baseados em webkit e refatora a estrutura HTML do plugin.
Obs: Tentei solucionar apenas definindo os tamanhos das divisórias, como disse para Igor essa semana no nosso chat privado. Mas acabou que o problema da …
=> Fix: Refactor plugin Linha do Tempo

app/nossas/apps/models/campaigns.py
Adiciona copy_relations ao plugin Nossas Cidades
- Adicione o plugin Nossas Cidades Project
- Selecione campanhas a serem mostradas no projeto
- Salve e publique a página
- Seja se as campanhas escolhidas estão na página publicada
=> Fix: Adiciona copy_relations ao plugin Nossas Cidades

app/contrib/ds/blocks/forms.py, app/contrib/ds/blocks/schemas/content_call_to_action.py, app/contrib/ds/blocks/templates/blocks/plugin/template_content_call_to_action.svg, app/nossas/design/static/design/scss/nossas.scss, app/requirements.txt
=> Feature: CTA schema

app/nossas/settings.py, app/requirements.txt
Durante o meu onboarding observamos alguns ajustes que seriam necessário para rodar o CMS. São apneas duas alterações no settings e no requirements.
Foi removido do app Nossas o Middleware `eleicao.middleware.EleicaoRedirectMiddleware`.
- `django-prometheus` : Prometheus é um sistema de monitoramento para serviços e aplicações.
=> fix(setup) update project dependencies

app/contrib/ds/blocks/cms_plugins.py, app/contrib/ds/blocks/tests/test_render_plugins.py
Corrige direção de Blocos flex com configuração Linha para Desktop e Mobile
=> fix(ds): block direction row and direction mobile row

app/contrib/bonde/models.py, app/votepeloclima/settings.py
=> fix(vote): keep base authenticate backend config on settings

app/contrib/oauth/views.py, app/votepeloclima/candidature/templates/candidature/dashboard.html, app/votepeloclima/candidature/views.py, app/votepeloclima/urls.py
Após autenticado na plataforma e com sua Candidatura habilitada para modo de edição o usuário pode alterar os dados da sua Candidatura e reenviar para avaliação
- Passo 1
- Passo 2
- Passo 3
=> [Feature] Editar Candidatura em acesso restrito a um usuário

app/votepeloclima/candidature/locations_utils.py
Refatora o get_choices de dentro do locations_utils.py referente aos fields de Estado e Municipio
=> Fix: Refactor locations_utils no Vote pelo Clima

app/org_eleicoes/votepeloclima/candidature/fields.py, app/org_eleicoes/votepeloclima/candidature/forms.py, app/org_eleicoes/votepeloclima/candidature/static/js/checkbox-text-widget.js, app/org_eleicoes/votepeloclima/candidature/templates/candidature/bandeiras_da_sua_candidatura.html, app/org_eleicoes/votepeloclima/candidature/templates/forms/widgets/switch.html, app/org_eleicoes/votepeloclima/candidature/templates/forms/widgets/textarea.html, app/org_eleicoes/votepeloclima/candidature/views.py
Adicionar campo Checkbox com Texto para usar no formulário de Bandeiras / Propostas
=> [Feature] Adiciona o campo CheckboxTextField

app/org_eleicoes/votepeloclima/candidature/templates/candidature/bandeiras_da_sua_candidatura.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/done.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/wizard_form.html, app/org_eleicoes/votepeloclima/candidature/views.py
=> Implementado o nome da próxima etapa no botão de Continuar

app/org_eleicoes/votepeloclima/candidature/testes/tests_inline_array.py
Implementado testes para o Field e Widget do campo inline implementado no Vote Pelo Clima.
=> feat(votepeloclima): Implemented tests for inline field and widget

app/org_eleicoes/votepeloclima/candidature/forms.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/candidature/views.py
Adiciona carousel do Bootstrap para Compromissos do Perfil da Candidatura
- Adicione appointments com valor True dentro de Candidaturas no Admin
- Acesse o Perfil da Candidatura e veja o carrossel em funcionamento
=> [Feature] Adiciona carrossel para Compromissos do Perfil da Candidatura

app/org_eleicoes/votepeloclima/candidature/views/base.py, app/org_eleicoes/votepeloclima/settings/base.py
=> fix(vote): add settings DEFAULT_FROM_EMAIL

app/org_eleicoes/votepeloclima/candidature/models.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
Resolvida a renderização dos nomes de estado e cidade, pois está sendo armazenado na base de dados os ids e não os nomes.
=> Fixed render city and state names on template

app/org_eleicoes/votepeloclima/candidature/forms.py
Mob fechou as bandeiras, agora são as seguintes:
[(Link para tela no figma) ](https://www.figma.com/design/yh38CZDMLo3QiQu70hTcrx/%5BVote-pelo-Clima%5D-Prot%C3%B3tipo?node-id=2964-133784&t=3GKyKFr1434pVPXJ-1)
Transporte e mobilidade
Transporte coletivo gratuito e de qualidade, modais com menos emissões e mobilidade ativa.
Gestão de resíduos
Compostagem de resíduos orgânicos, economia circular, mais iniciativas de catadores e catadoras de materiais recicláveis, uso de materiais biodegradáveis.
Povos e comunidades tradicionais 
Direitos, reconhecimento e valorização de conhecimentos e tecnologias de povos e comunidades tradicionais.
Educação climática
Ensino sobre meio ambiente e mudanças climáticas nas escolas, formação profissional para empregos verdes, formação de agentes populares para …
=> [Fix] Muda titulos e descrição das Propostas no Cadastro

app/org_eleicoes/votepeloclima/candidature/fields.py, app/org_eleicoes/votepeloclima/candidature/forms.py
Adiciona max_length ao Propostas e Minibio
=> [Fix] Adiciona max_length ao Propostas e Minibio

app/org_eleicoes/votepeloclima/settings/base.py, app/org_eleicoes/votepeloclima/templates/errors/404.html, app/org_eleicoes/votepeloclima/templates/errors/500.html
=> Implemented page not found template

app/org_eleicoes/eleicaodoano/eleicao/csv/choices.py
Esse conflito deve ter ficado para trás naquela tarefa de reorganizar o repositório e estrutura de workflow dos apps.
=> fix(eleicaodoano): Removed git conflict text from a file

app/org_eleicoes/votepeloclima/candidature/forms.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/captcha.html
Atualização do formulário de propostas e ajustes no texto da tela de captcha.
=> feat(votepeloclima): update proposes fields to 600 caracteres limit

app/org_eleicoes/votepeloclima/candidature/forms.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html
Adiciona novos copys ao Perfil de Candidatura
=> [Fix] Adiciona novos copys ao Perfil de Candidatura

app/org_eleicoes/votepeloclima/candidature/templates/candidature/checkout.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/submitted.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/wizard_base.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/wizard_form.html, app/org_eleicoes/votepeloclima/candidature/templates/forms/widgets/inline_array.html, app/org_eleicoes/votepeloclima/static/scss/custom.scss
Adiciona estilos do Cadastro da pessoa candidata para mobile
=> [Fix] Adiciona estilos do Cadastro da pessoa candidata para mobile

app/org_eleicoes/votepeloclima/candidature/static/scss/candidaturesearch.scss, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
=> fix(vote): change styles to list of candidatures

app/contrib/bonde/admin.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html
Possibilitar que os plugins de formulário enviem um e-mail customizado para o destinatário cadastrado.
=> Form Action para envio de E-mail

app/org_eleicoes/votepeloclima/candidature/views/base.py
Validação de email, nome e número da candidatura no formulário de Cadastro VPC
=> [Fix] Validação de email, nome e número da candidatura no formulário de Cadastro VPC

app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
=> hotfix(vote): add w-100 to conheça btn from candidate search

app/org_eleicoes/votepeloclima/candidature/static/scss/candidaturesearch.scss, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
=> Search refinement pt2

app/org_eleicoes/votepeloclima/candidature/static/scss/candidaturesearch.scss, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
Refatora Card de Buscar Candidaturas
hover:
=> [Fix] Refatora Card de Buscar Candidaturas

app/org_eleicoes/votepeloclima/candidature/templates/candidature/dashboard.html, app/org_eleicoes/votepeloclima/static/scss/custom.scss
Ajustes no mobile da Dashboard de Área da Candidatura
=> [Fix] Ajustes no mobile da Dashboard de Área da Candidatura

app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/static/scss/custom.scss
Refinamento da página de Perfil da Candidatura.
=> [Fix] Refinamento do Perfil da Candidatura VPC

app/org_eleicoes/votepeloclima/candidature/choices.py
Atualiza termos nas opções de Sexualidade da Candidatura. Alterar "gay" e "lesbica" para "homossexual".
Executar atualizaçao da base de dados apos publicar em produção.
=> [Hotfix] Atualiza termos nas opções de Sexualidade da Candidatura

app/org_eleicoes/votepeloclima/candidature/templates/candidature/dashboard.html
Remove gap dos botões da Area da Candidatura
=> [Design Review] Remove gap do grid da Area da Candidatura

app/org_eleicoes/votepeloclima/candidature/static/scss/candidaturesearch.scss, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
Adiciona flag "Eleito/a" e "2o Turno" nos cards da Buscar Candidaturas VPC
🚨  Esse PR necessita da implementação feita por @sergiomario no PR https://github.com/nossas/cms/pull/308/files
=> [Feature] Adiciona flag "Eleito/a" e "2o Turno" nos cards da Buscar Candidaturas VPC

app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/emails/register_done_subject.txt
Adiciona título de páginas do Perfil da Candidatura e Altera o Assunto do Email de Cadastro
=> [Fix] Adiciona título de páginas do Perfil da Candidatura e Altera o Assunto do Email de Cadastro

app/org_eleicoes/votepeloclima/candidature/forms/register.py
Remove a opção "Vereador" do Cadastro VPC
-  [x] Adiciona manualmente no forms as opções desejadas em intended_position
=> [Fix] Remove a opção "Vereador" do Cadastro VPC
