nossas/cms

app/eleicao/cms_plugins.py
Remove cache do plugin Listagem de Candidaturas
Objetivo principal é testar o filtro de candidaturas que está intermitente
=> fix(eleicao): remove cache for plugins with form

app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/plugins/candidate_list.html, app/eleicao/templates/eleicao/plugins/card.html
Ao tentar mudar de página na listagem com filtro, o filtro por estado não é mantido.
- https://app.asana.com/0/1161468210277385/1205366155573013/f
- https://app.asana.com/0/1161468210277385/1205324039429944/f
=> Fix: Filtro de Estado com Paginação na Lista de Candidaturas

app/eleicao/forms/create.py, app/eleicao/templates/eleicao/plugins/voter_form.html
Remove campo "newsletter" e troca a ordem o botão de Submit
=> Fix: Remove campo "newsletter" e troca a ordem o botão de Submit no Eleitor Form

app/eleicao/templates/eleicao/plugins/candidate_list.html
A interface da paginação estava mostrando todos os números para escolha da pagina acessada pela pessoa user. Esse PR limita esses números para mostrar apenas 5 números na paginação.
=> Fix: Adiciona limite de números na Pagination para 5

app/eleicao/cms_plugins.py, app/eleicao/templates/eleicao/plugins/voter_form.html, app/eleicao/templatetags/eleicao_candidate_tags.py
Adiciona VoterForm na templatetag para refatorar filtros de Estado e Cidade e considerar apenas os dados inseridos no formulário no momento do envio. 
- Realize uma busca com Estado e Cidade preenchidos
- Faça uma nova busca sem preencher Cidade e veja se filtra apenas por Estado (já que o o valor de Cidade não deve ser salvo no Eleitor anteriormente).
=> Fix: Adiciona VoterForm na templatetag para refatorar filtros de Estado e Cidade

app/eleicao/forms/candidate.py, app/eleicao/forms/fields.py, app/eleicao/views.py
Para aumentar o nível de segurança no momento dos cadastros de candidaturas, adicionar um campo reCaptcha para evitar submissões de bot, porém ao adicionar esse novo campo no formulário de várias etapas (SessionWizardView) percebemos um comportamento estranho na hora de enviar as informações do formulário para submissão.
Referência: https://github.com/torchbox/django-recaptcha/issues/115
- https://app.asana.com/0/0/1205319277260318/f
=> Fix: reCaptcha aplicado em formulários de várias etapas

app/eleicao/forms/candidate.py, app/eleicao/templates/eleicao/includes/form_control.html
Adiciona pontuação em texto de Cadastro de Candidates e utiliza a linguagem neutra no aviso de continuidade do cadastro.
=> Fix: Adiciona pontuação em texto de Cadastro de Candidates

app/contrib/actions/pressure/cms_plugins.py, app/contrib/actions/pressure/forms.py, app/contrib/actions/pressure/templates/pressure/pressure_plugin.html, app/tailwind/forms.py
Renderiza estilo do plugin de Pressão com base nas configurações da Widget no Bonde
=> [Hotfix] Ajustes no plugin de pressão

app/contrib/frontend/maps/static/maps/js/maps.js
Adiciona variação da linha no tooltip.
=> Fix: Adiciona variação da linha no tooltip

app/contrib/frontend/grid/templates/frontend/grid/plugins/grid.html
Adiciona w-full ao GridPlugin para não quebrar ao alterar o texto das colunas.
=> Fix: Adiciona w-full ao GridPlugin

app/contrib/actions/pressure/cms_plugins.py
Ao preencher o formulário de pressão de recarregar a página o contador não muda.
- Primeiro devemos considerar que o contador considera Ativistas destintos, ou seja se o mesmo Ativista fez 3 pressões, consideramos no calculo a pressão por 1 pessoa.
- Removemos o cache do plugin para evitar que o carregamento do número de pessoas que pressionaram não seja atualizado instataneamente
=> Fix: Contador de pessoas que pressionaram

app/contrib/frontend/maps/static/maps/js/maps.js
Adiciona filter e comparação para código + título no Mapa. Agora as pessoas usuárias podem buscar pelo título ou pelo código da linha no Mapa.
=> Fix: Adiciona filter e comparação para código + título no Mapa

app/contrib/frontend/maps/static/maps/css/maps.css, app/contrib/frontend/maps/static/maps/js/maps.js
Conforme citado pela Clareana e pela @sarahsoaresc, o Mapa não estava funcionando em iOS (Safari, Chrome). Esse PR refatora o fluxo de adição da linha e marcadores no Mapa seguindo o exemplo encontrado [aqui](https://tomickigrzegorz.github.io/leaflet-examples/#). Também foi desabilitado o uso de scroll ou touch para navegar no mapa, impossibilitando as pessoas usuárias de ficarem presas ao mapa. Os controles de zoom serão a única opção de navegar dentro do mapa.
=> Fix: Refatora uso de marcadores e linha para adequar as configs de iOS

app/contrib/actions/pressure/cms_plugins.py, app/contrib/actions/pressure/forms.py, app/contrib/actions/pressure/models.py, app/contrib/actions/pressure/static/bonde/css/edit-widget-form.css, app/contrib/actions/pressure/static/bonde/js/edit-widget-form.js, app/contrib/actions/pressure/static/pressure/js/array-widget.js, app/contrib/actions/pressure/static/pressure/js/pressure.js, app/contrib/actions/pressure/templates/pressure/pressure_plugin.html, app/contrib/bonde/forms.py, app/contrib/bonde/models.py, app/contrib/bonde/plugin_base.py
De maneira objetiva esse PR adiciona uma implementação base para Criar e Alterar configurações de Widget que antes eram feitas no Bonde.
**Criar Plugin de Pressão**
**Editar Plugin de Pressão**
=> [Feature] Adicionar e Editar Widget do Bonde direto no plugin do CMS

app/admin_styled/static/admin_styled/css/theme.css
Tive que sobreescrever a propriedade CSS `visibility: collapse` de todos os fieldsets para `unset` para que o JavaScript herdado do módulo oficial do Django possa funcionar. Obs: ou seja, tanto o link no ImagePlugin e o crop também já estavam implementados, eles só não estavam aparecendo no form por causa desse bug.
=> BugFix: Sobreescreve a propriedade CSS visibility de Fieldset para uset

app/nossas/plugins/cms_plugins/__init__.py, app/nossas/plugins/cms_plugins/box.py, app/nossas/plugins/cms_plugins/container.py, app/nossas/plugins/cms_plugins/header.py, app/nossas/plugins/forms/headerform.py, app/nossas/plugins/models/__init__.py, app/nossas/plugins/models/headermodel.py, app/nossas/plugins/templates/nossas/plugins/header.html, app/nossas/settings.py
Adiciona `Header` como plugin. Tive que adicionar três classes no CSS para que houvesse responsividade esperada a partir do que tá no Figma. 
https://www.figma.com/file/9aUCKe2Jt8twPVpd47Vffe/NOSSAS_layout_desktop_v2_elementos-coloridos_ajustes?type=design&node-id=25-14665&mode=dev
- Vá para uma página e adicione `Header` nos plugins
- Adicione uma cor de fundo
- Mude a imagem padrão para a fundo escolhido a partir do Figma
- Altere o texto de acordo com a preferencia
- Teste o cenário mobile > tablet > desktop
=> Feature: Adiciona HeaderPlugin

app/adp/settings/base.py, app/contrib/bonde/cms_plugins.py, app/contrib/bonde/models.py, app/contrib/ds/link/cms_plugins.py, app/contrib/ds/link/models.py, app/contrib/ds/link/templates/link/admin/plugin/change_form.html, app/contrib/ds/link/templates/link/plugins/submit.html, app/contrib/ds/link/tests.py, app/contrib/ds/static/ds/css/forms.scss, app/contrib/ds/static/ds/css/theme.scss
O plugin de Formulário é um fork de uma biblioteca chamada [djangocms_form_builder](https://github.com/nossas/djangocms-form-builder/tree/feature/add-input-fields-on-form-plugin). Ela faz estilização com base no Bootstrap5, apesar de ser uma biblioteca com boas funcionalidades, fazer uma customização não é tão simples.
O objetivo é tornar possível configurar novos plugins dentro do Formulário, adicionando liberdade para montar a estrutura do formulário.
- Inserir um plugin de `Formulário`
- Inserir um plugin de `Bloco` dentro desse `Formulário`
- Inserir um plugin de `Campo Texto` dentro do `Bloco`
- Inserir um plugin de `Botão` com **Comportamento do link** de **Enviar o formulário** dentro do `Formulário`
- Utiliza nova versão do `djangocms_form_builder` que precisa ser buildada
- Essa …
=> [Feature] Habilitar customizações no `djangocms_form_builder`

app/adp/settings/base.py, app/contrib/ds/picture/cms_plugins.py, app/contrib/ds/picture/tests/test_image_plugin.py
- Passo 1: Adicionar uma imagem e checar se ela se enquadra nos limites da página conforme o esperado.
- Passo 2: Caso seja alterado nas configurações avançadas a opção de USE RESPONSIVE IMAGE para 'Não' a imagem perde a classe `img-fluid` e deve manter as dimensões originais da imagem sem responsividade.
**Novos módulos**:
- `picture` : Foi criado um arquivo cms_plugin.py dentro de um app no Design System para sobscrever o comportamento da classe PicturePlugin do Django CMS.
=> feat(ds) implemented responsive images by default

app/org_eleicoes/votepeloclima/candidature/fields.py, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidate_profile.html, app/org_eleicoes/votepeloclima/candidature/views.py
Hoje as flags estão todas vindo como JSONField com titles em inglês para os badges (is_renew_energy, etc). Esse PR expõe `checkbox_label` de dentro de CheckboxTextField para ser utilizado dentro do Perfil de Candidatura.
- Vá para a página de candidatura e veja se as propostas tem Nome + Descrição
=> [Feature] Adiciona labels pra Bandeiras no Perfil da Candidatura

app/org_eleicoes/votepeloclima/candidature/fields.py, app/org_eleicoes/votepeloclima/candidature/forms.py, app/org_eleicoes/votepeloclima/candidature/static/js/inline-array-widget.js, app/org_eleicoes/votepeloclima/candidature/templates/forms/widgets/inline_array.html
Após o design review foi identificado o seguinte comportamento no botão de adicionar novos marcos ou redes sociais:
"Ao clicar em adicionar outra realização e rede social, adiciona 2 campos de uma vez (exemplo: se tem 1, e clico em adicionar outra, adiciona a 2 e 3)"
Agora a lógica só permite que seja adicionado mais um campo, caso o último não esteja vazio. Isso melhora a usabilidade e também corrige esse problema no JavaScript de double click.
=> fix(votepeloclima): Fixed add input script

app/org_eleicoes/votepeloclima/candidature/forms.py
Já tivemos algumas inscrições em que as candidaturas colocaram outro número no campo de numero da urna e confundiram o campo "nome na urna" com número, imaginamos que seja pq o label e o posicionamento dos campos estão gerando confusão.
ents/assets/c14681b5-a712-4c6c-b32c-037edb7db3ee">
=> Adjusts on ballot name and number id at register form

app/org_eleicoes/votepeloclima/candidature/fields.py
Perceberam um bug no campo de marcos quando é utilizado vírgulas no corpo do texto. Este PR corrige um problema onde o uso de vírgulas nos marcos (milestones) estava dividindo o texto em múltiplas entradas. A solução implementada agora trata as vírgulas dentro dos valores corretamente, permitindo que os marcos sejam salvos como uma lista JSON.
Foi alterado todo o tratamento do widget para manipulação de JSON. Utilizando JSON para encapsular os dados, você garante que textos complexos, incluindo aqueles com vírgulas, sejam tratados corretamente.
Se o usuário adicionasse dois marcos separados por vírgula, eles poderiam aparecer assim:
`"Em 2016 eu organizei um evento, e foi em Brasília, Outro marco importante"`
Com a nova abordagem, os dados são armazenados como uma lista JSON. Se o usuário …
=> Preserve commas in milestones without splitting entries

app/org_eleicoes/votepeloclima/candidature/fields.py
=> fix(votepeloclima): changed inline field delimiter

app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html
Com o aumento do número de pessoas candidatas a paginação está ficando desproporcional, e esse PR resolve limitando o número de páginas clicável.
=> fix(vote): Adjusted pagination layout at profile search

app/contrib/partners/templates/partners/partners_list.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/candidature_search.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/captcha.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/checkout.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/dashboard.html, app/org_eleicoes/votepeloclima/candidature/templates/candidature/wizard_form.html, app/org_eleicoes/votepeloclima/static/js/toggle_password.js, app/org_eleicoes/votepeloclima/static/scss/custom.scss, app/org_eleicoes/votepeloclima/templates/oauth/change_password.html, app/org_eleicoes/votepeloclima/templates/oauth/login.html, app/org_eleicoes/votepeloclima/templates/oauth/password_reset_done.html, app/org_eleicoes/votepeloclima/templates/oauth/password_reset_form.html, app/org_eleicoes/votepeloclima/templates/votepeloclima/base.html, app/org_eleicoes/votepeloclima/templates/votepeloclima/home.html, app/org_eleicoes/votepeloclima/templates/votepeloclima/menu_item.html
Esse PR tem todos os ajustes referentes a VPC front-end.
=> [Fix] Refinamento geral de Frontend da plataforma Vote Pelo Clima

deploy/docker-compose.yml
Adicionar o VPC como novo serviço no arquivo de deploy do CMS, para que ele fique como um stack no servidor do CMS, assim como os outros sites.
=> Added vpc service config on docker compose file

app/org_nossas/nossas/plugins/templates/nossas/plugins/pdf.html
A visualização de PDFs está com resolução baixa no site do Nossas.
Foram ajustados alguns parâmetros de configuração no Javascript do plugin.
=> Adjusted pdf viewer styles
